version: "3.9"

services:
  cyhealth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      API_KEY: 84362c58a5ab5305502e893e868e70b2
    volumes:
      - ./cyhealth.ini:/etc/cyhealth.ini
